name: deployment
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/sysadmin/projects/flow-wp-dev/wp-content/themes/flow-wp &&
            git pull origin dev &&
            sudo docker run --rm -v .:/app --workdir /app node:lts-buster npm run build
    
